// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epydspajwvomqbkfdkiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVweWRzcGFqd3ZvbXFia2Zka2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTI5NTEsImV4cCI6MjA1ODg4ODk1MX0.AWlMYna_MAGJnZl0Zswtkt8mJ5MQ7r4MsNANEGMxiIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);